import { prisma } from '@/lib/db';
import { canAttemptAutoFix } from './quota';
import { findRelevantFiles } from './source-locator';
import { redactNetworkTrace, redactConsole, type NetworkRequestRecord, type ConsoleEntry } from './redactor';
import { analyzeError } from './claude';
import { allocateBranchName, createBranch, commitFiles, mergeBranchToBase, isGitHubConfigured } from './github';
import { sendInitialErrorNotification, sendCompletionNotification } from './email';

const AUTO_MERGE_ENABLED = (process.env.ERROR_AUTO_MERGE_ENABLED || 'true').toLowerCase() !== 'false';

/**
 * Drive a single ErrorAutoFix through its lifecycle. Designed to be called
 * fire-and-forget from an API route via @vercel/functions waitUntil() so the
 * HTTP response goes out immediately.
 *
 * Idempotent on reprocessing: if status is already terminal, no-ops.
 */
export async function processFix(autoFixId: string): Promise<void> {
  const fix = await prisma.errorAutoFix.findUnique({ where: { id: autoFixId } });
  if (!fix) return;
  if (['merged', 'branch_created', 'no_fix_proposed', 'failed', 'reverted'].includes(fix.status)) return;

  // 1. Initial notification — fire and don't block on email
  prisma.errorAutoFix
    .findUnique({ where: { id: autoFixId }, include: { reporter: { select: { id: true, name: true, email: true } } } })
    .then((withReporter) => withReporter && sendInitialErrorNotification(withReporter))
    .catch((e) => console.error('[error-fixer] sendInitialErrorNotification failed:', e));

  // 2. Quota check
  const quota = await canAttemptAutoFix({ url: fix.url, source: fix.source as 'user_reported' | 'auto_detected' });
  if (!quota.allowed) {
    await markFailed(autoFixId, quota.reason || 'Quota check failed');
    return;
  }

  await prisma.errorAutoFix.update({ where: { id: autoFixId }, data: { status: 'analyzing' } });

  try {
    // 3. Find relevant source files
    const sources = await findRelevantFiles(fix.url);

    // 4. Sanitise telemetry
    const network = redactNetworkTrace(fix.networkTrace as NetworkRequestRecord[] | null);
    const consoleErrors = redactConsole(fix.consoleErrors as ConsoleEntry[] | null);

    // 5. Ask Claude
    const result = await analyzeError({
      source: fix.source as 'user_reported' | 'auto_detected',
      userDescription: fix.userDescription,
      superAdminMessage: fix.superAdminMessage,
      url: fix.url,
      httpStatus: fix.httpStatus,
      errorMessage: fix.errorMessage,
      errorStack: fix.errorStack,
      network,
      consoleErrors,
      sources,
    });

    await prisma.errorAutoFix.update({
      where: { id: autoFixId },
      data: {
        claudeAnalysis: result.analysis,
        claudeProposedChanges: result.fileChanges as unknown as object,
      },
    });

    // 6. No fix → done
    if (!result.fileChanges.length) {
      const updated = await prisma.errorAutoFix.update({
        where: { id: autoFixId },
        data: {
          status: 'no_fix_proposed',
          processingError: result.noFixReason || null,
          notifiedAt: new Date(),
        },
      });
      await sendCompletionNotification(updated);
      return;
    }

    // 7. GitHub disabled → store the proposal but stop short of branching
    if (!isGitHubConfigured()) {
      const updated = await prisma.errorAutoFix.update({
        where: { id: autoFixId },
        data: {
          status: 'no_fix_proposed',
          processingError: 'GitHub not configured (GITHUB_TOKEN/OWNER/REPO missing) — proposal saved but no branch created',
          notifiedAt: new Date(),
        },
      });
      await sendCompletionNotification(updated);
      return;
    }

    // 8. Allocate branch and create it
    const branchName = await allocateBranchName();
    await createBranch(branchName);

    // 9. Commit
    const summaryLine = (fix.errorMessage || fix.userDescription || 'unknown error').slice(0, 60).replace(/\s+/g, ' ');
    const commitMessage = `[ai-fix] ${summaryLine}\n\nAuto-generated by Acumon self-healing system. Reference: ${autoFixId}\nSource: ${fix.source}\n\n${result.analysis}`;
    const { commitSha } = await commitFiles({
      branch: branchName,
      files: result.fileChanges.map((c) => ({ path: c.path, contents: c.newContents })),
      message: commitMessage,
    });

    await prisma.errorAutoFix.update({
      where: { id: autoFixId },
      data: { branchName, commitSha, status: 'branch_created' },
    });

    // 10. Auto-merge if applicable (only auto_detected, only if kill switch on)
    if (fix.source === 'auto_detected' && AUTO_MERGE_ENABLED) {
      try {
        const { mergeSha } = await mergeBranchToBase(branchName, `[ai-fix] auto-merge ${branchName}`);
        const updated = await prisma.errorAutoFix.update({
          where: { id: autoFixId },
          data: {
            status: 'merged',
            autoMerged: true,
            mergedAt: new Date(),
            commitSha: mergeSha,
            notifiedAt: new Date(),
          },
        });
        await sendCompletionNotification(updated);
        return;
      } catch (mergeErr: unknown) {
        const msg = mergeErr instanceof Error ? mergeErr.message : String(mergeErr);
        const updated = await prisma.errorAutoFix.update({
          where: { id: autoFixId },
          data: {
            status: 'branch_created',
            processingError: `Auto-merge failed: ${msg}. Branch is available for manual merge.`,
            notifiedAt: new Date(),
          },
        });
        await sendCompletionNotification(updated);
        return;
      }
    }

    // User-reported, or kill switch off → leave as branch_created
    const updated = await prisma.errorAutoFix.update({
      where: { id: autoFixId },
      data: { notifiedAt: new Date() },
    });
    await sendCompletionNotification(updated);
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[error-fixer] processFix failed:', err);
    await markFailed(autoFixId, msg);
  }
}

async function markFailed(autoFixId: string, reason: string): Promise<void> {
  try {
    const updated = await prisma.errorAutoFix.update({
      where: { id: autoFixId },
      data: { status: 'failed', processingError: reason, notifiedAt: new Date() },
    });
    await sendCompletionNotification(updated);
  } catch (e) {
    console.error('[error-fixer] markFailed failed:', e);
  }
}

/**
 * Hook from server-side error logging. Creates an ErrorAutoFix tied to an
 * existing ErrorLog row and kicks off the orchestrator.
 *
 * Returns the autoFixId or null if the trigger was skipped.
 */
export async function triggerAutoFixForLog(errorLogId: string): Promise<string | null> {
  const log = await prisma.errorLog.findUnique({ where: { id: errorLogId } });
  if (!log) return null;
  if (log.severity === 'warning') return null; // skip warnings

  // Don't double-fix the same log
  const existing = await prisma.errorAutoFix.findUnique({ where: { errorLogId } });
  if (existing) return existing.id;

  // Quota check up-front so we don't even create the row if blocked — keeps
  // the table clean
  const quota = await canAttemptAutoFix({ url: log.route, source: 'auto_detected' });
  if (!quota.allowed) {
    console.log(`[error-fixer] Skipping autoFix for log ${errorLogId}: ${quota.reason}`);
    return null;
  }

  const fix = await prisma.errorAutoFix.create({
    data: {
      errorLogId,
      source: 'auto_detected',
      reporterId: log.userId,
      firmId: log.firmId,
      url: log.route,
      errorMessage: log.message,
      errorStack: log.stack,
      status: 'pending',
    },
  });

  // Fire and forget — the API route caller wraps in waitUntil()
  void processFix(fix.id);
  return fix.id;
}
