-- Portal messaging — WeChat channel additions.
-- Idempotent; safe to re-run on any Supabase database.
-- Run in Supabase SQL Editor on production before deploying.
--
-- WeChat works differently from the other channels: there is no
-- "phone number" we can paste in. The user scans a QR generated by
-- the firm's Official Account (公众号), follows it, and the Account's
-- webhook fires with the user's OpenID + the scene code we put on
-- the QR. We bind that OpenID to the portal user via wechat_link_code
-- and then send messages by OpenID via the customer-service or
-- template-message APIs.

ALTER TABLE client_portal_users
  ADD COLUMN IF NOT EXISTS wechat_open_id             TEXT NULL,
  ADD COLUMN IF NOT EXISTS wechat_nickname            TEXT NULL,
  ADD COLUMN IF NOT EXISTS wechat_opt_in              BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS wechat_link_code           TEXT NULL,
  ADD COLUMN IF NOT EXISTS wechat_link_expires_at     TIMESTAMPTZ NULL;

-- Plain unique index on wechat_link_code. Postgres treats NULLs as
-- distinct in a unique index, so multiple users with NULL link_code
-- don't collide. This matches what Prisma generates from `@unique`
-- in schema.prisma; a previous version used a partial-unique
-- `WHERE col IS NOT NULL` which collided with Prisma on every deploy.
CREATE UNIQUE INDEX IF NOT EXISTS client_portal_users_wechat_link_code_key
  ON client_portal_users (wechat_link_code);

CREATE INDEX IF NOT EXISTS client_portal_users_wechat_open_id_idx
  ON client_portal_users (wechat_open_id);

ALTER TABLE client_portal_staff_members
  ADD COLUMN IF NOT EXISTS wechat_opt_in BOOLEAN NOT NULL DEFAULT FALSE;
