'use client';

import { useState, useEffect } from 'react';
import { Loader2, CheckCircle2, Clock, Users, User, Bot, AlertTriangle } from 'lucide-react';

interface OutstandingItem {
  id: string;
  type: 'flow_task' | 'portal_request' | 'evidence_request' | 'review_point';
  title: string;
  description?: string;
  source: 'flow' | 'manual';  // flow = generated by test flow, manual = created by user
  assignedTo?: string;
  status: 'pending' | 'in_progress' | 'awaiting_client' | 'awaiting_team' | 'complete';
  createdAt: string;
  fsLine?: string;
  testName?: string;
  flowNodeType?: string; // action, wait, decision
  priority?: 'normal' | 'high' | 'urgent';
}

interface Props {
  engagementId: string;
  onCountsChange?: (teamCount: number, clientCount: number) => void;
}

// Colour configs for item types
const TYPE_STYLES: Record<string, { bg: string; text: string; icon: typeof Bot; label: string }> = {
  flow_task:         { bg: 'bg-teal-100', text: 'text-teal-700', icon: Bot, label: 'Flow Task' },
  portal_request:    { bg: 'bg-sky-100', text: 'text-sky-700', icon: Users, label: 'Portal Request' },
  evidence_request:  { bg: 'bg-blue-100', text: 'text-blue-700', icon: Users, label: 'Evidence Request' },
  review_point:      { bg: 'bg-amber-100', text: 'text-amber-700', icon: AlertTriangle, label: 'Review Point' },
};

const PRIORITY_STYLES: Record<string, string> = {
  urgent: 'border-l-4 border-l-red-500',
  high: 'border-l-4 border-l-amber-400',
  normal: '',
};

export function EngagementOutstandingTab({ engagementId, onCountsChange }: Props) {
  const [items, setItems] = useState<OutstandingItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    loadItems();
  }, [engagementId]);

  async function loadItems() {
    setLoading(true);
    try {
      const res = await fetch(`/api/engagements/${engagementId}/outstanding`);
      if (res.ok) {
        const data = await res.json();
        setItems(data.items || []);
      }
    } catch {
      // Will show empty state — API may not exist yet
      setItems([]);
    } finally {
      setLoading(false);
    }
  }

  // Split into sections
  const teamItems = items.filter(i => i.status === 'awaiting_team' || i.status === 'pending' || i.status === 'in_progress');
  const clientItems = items.filter(i => i.status === 'awaiting_client');
  const completedItems = items.filter(i => i.status === 'complete');

  // Report counts to parent for tab dots
  useEffect(() => {
    onCountsChange?.(teamItems.length, clientItems.length);
  }, [teamItems.length, clientItems.length, onCountsChange]);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16">
        <Loader2 className="h-6 w-6 animate-spin text-blue-500" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Summary bar */}
      <div className="flex items-center gap-4">
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-teal-50 border border-teal-200">
          <div className="w-6 h-6 rounded-full bg-teal-500 text-white text-xs font-bold flex items-center justify-center">
            {teamItems.length}
          </div>
          <span className="text-sm font-medium text-teal-700">Team Action Required</span>
        </div>
        <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-orange-50 border border-orange-200">
          <div className="w-6 h-6 rounded-full bg-orange-500 text-white text-xs font-bold flex items-center justify-center">
            {clientItems.length}
          </div>
          <span className="text-sm font-medium text-orange-700">Awaiting Client</span>
        </div>
        {completedItems.length > 0 && (
          <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-green-50 border border-green-200">
            <div className="w-6 h-6 rounded-full bg-green-500 text-white text-xs font-bold flex items-center justify-center">
              {completedItems.length}
            </div>
            <span className="text-sm font-medium text-green-700">Completed</span>
          </div>
        )}
      </div>

      {/* Two-column layout */}
      <div className="grid grid-cols-2 gap-6">
        {/* Team Action Required */}
        <div>
          <h3 className="text-sm font-bold text-teal-700 uppercase tracking-wide mb-3 flex items-center gap-2">
            <User className="h-4 w-4" />
            Team Action Required
          </h3>
          {teamItems.length === 0 ? (
            <div className="border rounded-lg p-8 text-center bg-slate-50">
              <CheckCircle2 className="h-8 w-8 text-green-400 mx-auto mb-2" />
              <p className="text-sm text-slate-400">No team actions outstanding</p>
            </div>
          ) : (
            <div className="space-y-2">
              {teamItems.map(item => (
                <OutstandingCard key={item.id} item={item} />
              ))}
            </div>
          )}
        </div>

        {/* Awaiting Client */}
        <div>
          <h3 className="text-sm font-bold text-orange-700 uppercase tracking-wide mb-3 flex items-center gap-2">
            <Users className="h-4 w-4" />
            Awaiting Client Response
          </h3>
          {clientItems.length === 0 ? (
            <div className="border rounded-lg p-8 text-center bg-slate-50">
              <CheckCircle2 className="h-8 w-8 text-green-400 mx-auto mb-2" />
              <p className="text-sm text-slate-400">No items awaiting client</p>
            </div>
          ) : (
            <div className="space-y-2">
              {clientItems.map(item => (
                <OutstandingCard key={item.id} item={item} />
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Completed section (collapsible) */}
      {completedItems.length > 0 && (
        <details className="mt-4">
          <summary className="text-sm font-medium text-slate-500 cursor-pointer hover:text-slate-700">
            Completed items ({completedItems.length})
          </summary>
          <div className="mt-2 space-y-2 opacity-60">
            {completedItems.map(item => (
              <OutstandingCard key={item.id} item={item} />
            ))}
          </div>
        </details>
      )}
    </div>
  );
}

function OutstandingCard({ item }: { item: OutstandingItem }) {
  const style = TYPE_STYLES[item.type] || TYPE_STYLES.flow_task;
  const Icon = style.icon;
  const priorityClass = PRIORITY_STYLES[item.priority || 'normal'];

  return (
    <div className={`border rounded-lg p-3 bg-white hover:shadow-sm transition-shadow ${priorityClass}`}>
      <div className="flex items-start gap-2.5">
        <div className={`w-7 h-7 rounded-lg ${item.source === 'flow' ? 'bg-teal-100' : 'bg-slate-100'} flex items-center justify-center shrink-0 mt-0.5`}>
          <Icon className={`h-3.5 w-3.5 ${item.source === 'flow' ? 'text-teal-600' : 'text-slate-500'}`} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-0.5">
            <span className="text-sm font-semibold text-slate-800">{item.title}</span>
            <span className={`text-[9px] font-medium px-1.5 py-0.5 rounded-full ${style.bg} ${style.text}`}>
              {style.label}
            </span>
            {item.source === 'flow' && (
              <span className="text-[9px] font-medium px-1.5 py-0.5 rounded-full bg-teal-50 text-teal-600 border border-teal-200">
                Flow
              </span>
            )}
          </div>
          {item.description && (
            <p className="text-xs text-slate-500 leading-relaxed">{item.description}</p>
          )}
          <div className="flex items-center gap-3 mt-1.5 text-[10px] text-slate-400">
            {item.fsLine && <span>FS: {item.fsLine}</span>}
            {item.testName && <span>Test: {item.testName}</span>}
            {item.assignedTo && <span>Assigned: {item.assignedTo}</span>}
            <span className="flex items-center gap-0.5">
              <Clock className="h-3 w-3" />
              {new Date(item.createdAt).toLocaleDateString('en-GB', { day: 'numeric', month: 'short' })}
            </span>
          </div>
        </div>
        {item.status === 'complete' && (
          <CheckCircle2 className="h-4 w-4 text-green-500 shrink-0" />
        )}
        {item.priority === 'urgent' && (
          <span className="text-[9px] font-bold text-red-600 bg-red-50 px-1.5 py-0.5 rounded shrink-0">URGENT</span>
        )}
      </div>
    </div>
  );
}
