import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { prisma } from '@/lib/db';
import { verifySummaryJobAccess } from '@/lib/client-access';
import { sendEmail, type EmailAttachment } from '@/lib/email';
import { generateDocSummaryPdf, type Finding, type FileInfo } from '@/lib/doc-summary-pdf';
import { logActivity, logError, requestContext } from '@/lib/logger';

export const maxDuration = 60;

export async function POST(req: Request) {
  const session = await auth();
  if (!session?.user?.twoFactorVerified) {
    return NextResponse.json({ error: 'Unauthorised' }, { status: 401 });
  }

  let body: { jobId?: string; recipientEmail?: string; recipientName?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { jobId, recipientEmail, recipientName } = body;
  if (!jobId) return NextResponse.json({ error: 'jobId required' }, { status: 400 });
  if (!recipientEmail) return NextResponse.json({ error: 'recipientEmail required' }, { status: 400 });

  const jobAccess = await verifySummaryJobAccess(
    session.user as { id: string; firmId: string; isSuperAdmin?: boolean },
    jobId,
  );
  if (!jobAccess.allowed) {
    return NextResponse.json({ error: jobAccess.reason || 'Forbidden' }, { status: 403 });
  }

  try {
    const job = await prisma.docSummaryJob.findUnique({
      where: { id: jobId },
      include: {
        client: { select: { clientName: true } },
        user: { select: { name: true, firm: { select: { name: true } } } },
        files: {
          orderBy: { createdAt: 'asc' },
          select: {
            id: true,
            originalName: true,
            fileSize: true,
            pageCount: true,
            documentDescription: true,
            createdAt: true,
          },
        },
        findings: {
          orderBy: [{ fileId: 'asc' }, { sortOrder: 'asc' }],
        },
      },
    });

    if (!job) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    const clientName = job.client.clientName;
    const firmName = job.user.firm.name;
    const userName = job.user.name;
    const exportDate = new Date();

    // Build file info array
    const files: FileInfo[] = job.files.map((f) => ({
      id: f.id,
      originalName: f.originalName,
      fileSize: f.fileSize,
      pageCount: f.pageCount,
      documentDescription: f.documentDescription || null,
      createdAt: f.createdAt.toISOString(),
      uploadedBy: userName,
    }));

    // Build findings array
    const fileNameMap = new Map(job.files.map((f) => [f.id, f.originalName]));
    const findings: Finding[] = job.findings.map((f) => ({
      id: f.id,
      area: f.area,
      finding: f.finding,
      clauseReference: f.clauseReference,
      isSignificantRisk: f.isSignificantRisk,
      aiSignificantRisk: f.aiSignificantRisk,
      userResponse: f.userResponse,
      addToTesting: f.addToTesting,
      reviewed: f.reviewed,
      fileId: f.fileId,
      fileName: fileNameMap.get(f.fileId) || 'Unknown',
      accountingImpact: f.accountingImpact ?? null,
      auditImpact: f.auditImpact ?? null,
    }));

    // Generate PDF
    const pdfBytes = await generateDocSummaryPdf({
      jobId,
      findings,
      files,
      clientName,
      firmName,
      userName,
      exportDate,
    });

    const pdfBase64 = Buffer.from(pdfBytes).toString('base64');
    const safeClientName = clientName.replace(/[^a-zA-Z0-9_-]/g, '_');
    const dateStr = exportDate.toISOString().slice(0, 10);
    const filename = `Document-Summary-${safeClientName}-${dateStr}.pdf`;

    const formattedDate = exportDate.toLocaleDateString('en-GB', {
      day: 'numeric',
      month: 'long',
      year: 'numeric',
    });

    const displayName = recipientName || recipientEmail;
    const subject = `Document Summary Report \u2014 ${clientName}`;
    const html = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #1e3a5f 0%, #2563eb 100%); padding: 30px; border-radius: 8px 8px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">Acumon Intelligence</h1>
        </div>
        <div style="background: #f8fafc; padding: 30px; border-radius: 0 0 8px 8px; border: 1px solid #e2e8f0;">
          <p style="color: #374151; font-size: 16px;">Hello ${displayName},</p>
          <p style="color: #374151; font-size: 16px;">
            Please find attached the Document Summary report for <strong>${clientName}</strong>,
            generated by ${userName} on ${formattedDate}.
          </p>
          <p style="color: #6b7280; font-size: 14px; margin-top: 24px;">
            This report was generated using the Acumon Intelligence platform.
          </p>
        </div>
      </div>
    `;

    const attachment: EmailAttachment = {
      name: filename,
      contentType: 'application/pdf',
      contentInBase64: pdfBase64,
    };

    console.log(`[DocSummary:SendEmail] Sending to ${recipientEmail} | jobId=${jobId} | client=${clientName}`);

    const result = await sendEmail(recipientEmail, subject, html, {
      displayName,
      attachments: [attachment],
    });

    console.log(`[DocSummary:SendEmail] Sent | messageId=${result.messageId}`);

    // Non-blocking activity log
    logActivity({
      userId: session.user.id,
      firmId: (session.user as { firmId?: string }).firmId,
      clientId: job.clientId,
      action: 'send_email',
      tool: 'doc-summary',
      detail: { jobId, recipient: recipientEmail },
      ipAddress: req.headers.get('x-forwarded-for') || req.headers.get('x-real-ip') || undefined,
      userAgent: req.headers.get('user-agent') || undefined,
    });

    return NextResponse.json({ success: true, messageId: result.messageId });
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    console.error(`[DocSummary:SendEmail] Failed | jobId=${jobId} | error=${msg}`);
    logError({
      userId: session.user.id,
      route: '/api/doc-summary/send-email',
      tool: 'doc-summary',
      message: msg,
      stack: error instanceof Error ? error.stack : undefined,
      context: requestContext(req),
    });
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
